### ISSUE TITLE
Audio record directly from the app

### ISSUE THREAD

**Issue by smlavoie** [MaharaProject/mahara-mobile-cordova#36]
Despite having the possible authorisation to use microphone, the application does not seem to show an option to directly record audio from the mobile app (and then to upload it in the cloud).

**Comment by agwells** [comment]
Hm, I looked into this a year ago for the Mahara website, and the options at the time weren't great. It was basically, use Flash or Java applets, or use `<input type="file" accept="audio/*">`. Flash & Java applets of course don't work on the mobile web, and `<input type="file" accept="audio/*">` didn't work in iOS because it has no default audio recording app (it launches the video app instead).

But Googling now, I see there's a Cordova media capture plugin, which can do audio recording: https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-media-capture/

Apparently for Android it launches the default audio recorder, and for iOS it sounds like it uses native code to launch a simple audio recorder interface. So, that would probably be suitable, if we can get the development resources to fund it.

**Comment by agwells** [comment]
Oh, and bonus points, we're already using the cordova-plugin-media-capture plugin! It's how we access the photo library. That's probably why we're asking for microphone permissions. Hm, I think we could probably remove that permission now, though. It may have been required under earlier versions of Cordova, but newer versions are a little better about managing optional plugin permissions.

**Comment by anitsirk** [comment]
We haven't yet implemented the audio recording. It should be possible as Aaron wrote, but we haven't had the time to look into it.

**Comment by anitsirk** [comment]
Implemented into Mahara Mobile 1.4.0, which is in the process of being released.
